// src/config/entityRegistry.ts

export const ENTITY_REGISTRY: Record<string, { internalCode: string, shortName: string, name: string, path: string }> = {
    // ==========================================
    // ⚾️ BASEBALL - MLB (30 TEAMS) - SPORT: 01
    // ==========================================
    "Mpt_MLB01": { internalCode: "01_01_NYY", shortName: "NYY", name: "New York Yankees", path: "/assets/baseball/mlb/nyy.png" },
    "Mpt_MLB02": { internalCode: "01_01_BOS", shortName: "BOS", name: "Boston Red Sox", path: "/assets/baseball/mlb/bos.png" },
    "Mpt_MLB03": { internalCode: "01_01_BAL", shortName: "BAL", name: "Baltimore Orioles", path: "/assets/baseball/mlb/bal.png" },
    "Mpt_MLB04": { internalCode: "01_01_TB", shortName: "TB", name: "Tampa Bay Rays", path: "/assets/baseball/mlb/tb.png" },
    "Mpt_MLB05": { internalCode: "01_01_TOR", shortName: "TOR", name: "Toronto Blue Jays", path: "/assets/baseball/mlb/tor.png" },
    "Mpt_MLB06": { internalCode: "01_01_CWS", shortName: "CWS", name: "Chicago White Sox", path: "/assets/baseball/mlb/cws.png" },
    "Mpt_MLB07": { internalCode: "01_01_CLE", shortName: "CLE", name: "Cleveland Guardians", path: "/assets/baseball/mlb/cle.png" },
    "Mpt_MLB08": { internalCode: "01_01_DET", shortName: "DET", name: "Detroit Tigers", path: "/assets/baseball/mlb/det.png" },
    "Mpt_MLB09": { internalCode: "01_01_KC", shortName: "KC", name: "Kansas City Royals", path: "/assets/baseball/mlb/kc.png" },
    "Mpt_MLB10": { internalCode: "01_01_MIN", shortName: "MIN", name: "Minnesota Twins", path: "/assets/baseball/mlb/min.png" },
    "Mpt_MLB11": { internalCode: "01_01_HOU", shortName: "HOU", name: "Houston Astros", path: "/assets/baseball/mlb/hou.png" },
    "Mpt_MLB12": { internalCode: "01_01_LAA", shortName: "LAA", name: "Los Angeles Angels", path: "/assets/baseball/mlb/laa.png" },
    "Mpt_MLB13": { internalCode: "01_01_OAK", shortName: "OAK", name: "Oakland Athletics", path: "/assets/baseball/mlb/oak.png" },
    "Mpt_MLB14": { internalCode: "01_01_SEA", shortName: "SEA", name: "Seattle Mariners", path: "/assets/baseball/mlb/sea.png" },
    "Mpt_MLB15": { internalCode: "01_01_TEX", shortName: "TEX", name: "Texas Rangers", path: "/assets/baseball/mlb/tex.png" },
    "Mpt_MLB16": { internalCode: "01_01_ATL", shortName: "ATL", name: "Atlanta Braves", path: "/assets/baseball/mlb/atl.png" },
    "Mpt_MLB17": { internalCode: "01_01_MIA", shortName: "MIA", name: "Miami Marlins", path: "/assets/baseball/mlb/mia.png" },
    "Mpt_MLB18": { internalCode: "01_01_NYM", shortName: "NYM", name: "New York Mets", path: "/assets/baseball/mlb/nym.png" },
    "Mpt_MLB19": { internalCode: "01_01_PHI", shortName: "PHI", name: "Philadelphia Phillies", path: "/assets/baseball/mlb/phi.png" },
    "Mpt_MLB20": { internalCode: "01_01_WSH", shortName: "WSH", name: "Washington Nationals", path: "/assets/baseball/mlb/wsh.png" },
    "Mpt_MLB21": { internalCode: "01_01_CHC", shortName: "CHC", name: "Chicago Cubs", path: "/assets/baseball/mlb/chc.png" },
    "Mpt_MLB22": { internalCode: "01_01_CIN", shortName: "CIN", name: "Cincinnati Reds", path: "/assets/baseball/mlb/cin.png" },
    "Mpt_MLB23": { internalCode: "01_01_MIL", shortName: "MIL", name: "Milwaukee Brewers", path: "/assets/baseball/mlb/mil.png" },
    "Mpt_MLB24": { internalCode: "01_01_PIT", shortName: "PIT", name: "Pittsburgh Pirates", path: "/assets/baseball/mlb/pit.png" },
    "Mpt_MLB25": { internalCode: "01_01_STL", shortName: "STL", name: "St. Louis Cardinals", path: "/assets/baseball/mlb/stl.png" },
    "Mpt_MLB26": { internalCode: "01_01_ARI", shortName: "ARI", name: "Arizona Diamondbacks", path: "/assets/baseball/mlb/ari.png" },
    "Mpt_MLB27": { internalCode: "01_01_COL", shortName: "COL", name: "Colorado Rockies", path: "/assets/baseball/mlb/col.png" },
    "Mpt_MLB28": { internalCode: "01_01_LAD", shortName: "LAD", name: "Los Angeles Dodgers", path: "/assets/baseball/mlb/lad.png" },
    "Mpt_MLB29": { internalCode: "01_01_SD", shortName: "SD", name: "San Diego Padres", path: "/assets/baseball/mlb/sd.png" },
    "Mpt_MLB30": { internalCode: "01_01_SF", shortName: "SF", name: "San Francisco Giants", path: "/assets/baseball/mlb/sf.png" },

    // ==========================================
    // 🏀 BASKETBALL - NBA (30 TEAMS) - SPORT: 03
    // ==========================================
    "Mpt_NBA01": { internalCode: "03_01_BOS", shortName: "BOS", name: "Boston Celtics", path: "/assets/basketball/nba/bos.png" },
    "Mpt_NBA02": { internalCode: "03_01_BKN", shortName: "BKN", name: "Brooklyn Nets", path: "/assets/basketball/nba/bkn.png" },
    "Mpt_NBA03": { internalCode: "03_01_NYK", shortName: "NYK", name: "New York Knicks", path: "/assets/basketball/nba/nyk.png" },
    "Mpt_NBA04": { internalCode: "03_01_PHI", shortName: "PHI", name: "Philadelphia 76ers", path: "/assets/basketball/nba/phi.png" },
    "Mpt_NBA05": { internalCode: "03_01_TOR", shortName: "TOR", name: "Toronto Raptors", path: "/assets/basketball/nba/tor.png" },
    "Mpt_NBA06": { internalCode: "03_01_CHI", shortName: "CHI", name: "Chicago Bulls", path: "/assets/basketball/nba/chi.png" },
    "Mpt_NBA07": { internalCode: "03_01_CLE", shortName: "CLE", name: "Cleveland Cavaliers", path: "/assets/basketball/nba/cle.png" },
    "Mpt_NBA08": { internalCode: "03_01_DET", shortName: "DET", name: "Detroit Pistons", path: "/assets/basketball/nba/det.png" },
    "Mpt_NBA09": { internalCode: "03_01_IND", shortName: "IND", name: "Indiana Pacers", path: "/assets/basketball/nba/ind.png" },
    "Mpt_NBA10": { internalCode: "03_01_MIL", shortName: "MIL", name: "Milwaukee Bucks", path: "/assets/basketball/nba/mil.png" },
    "Mpt_NBA11": { internalCode: "03_01_ATL", shortName: "ATL", name: "Atlanta Hawks", path: "/assets/basketball/nba/atl.png" },
    "Mpt_NBA12": { internalCode: "03_01_CHA", shortName: "CHA", name: "Charlotte Hornets", path: "/assets/basketball/nba/cha.png" },
    "Mpt_NBA13": { internalCode: "03_01_MIA", shortName: "MIA", name: "Miami Heat", path: "/assets/basketball/nba/mia.png" },
    "Mpt_NBA14": { internalCode: "03_01_ORL", shortName: "ORL", name: "Orlando Magic", path: "/assets/basketball/nba/orl.png" },
    "Mpt_NBA15": { internalCode: "03_01_WAS", shortName: "WAS", name: "Washington Wizards", path: "/assets/basketball/nba/was.png" },
    "Mpt_NBA16": { internalCode: "03_01_DEN", shortName: "DEN", name: "Denver Nuggets", path: "/assets/basketball/nba/den.png" },
    "Mpt_NBA17": { internalCode: "03_01_MIN", shortName: "MIN", name: "Minnesota Timberwolves", path: "/assets/basketball/nba/min.png" },
    "Mpt_NBA18": { internalCode: "03_01_OKC", shortName: "OKC", name: "Oklahoma City Thunder", path: "/assets/basketball/nba/okc.png" },
    "Mpt_NBA19": { internalCode: "03_01_POR", shortName: "POR", name: "Portland Trail Blazers", path: "/assets/basketball/nba/por.png" },
    "Mpt_NBA20": { internalCode: "03_01_UTA", shortName: "UTA", name: "Utah Jazz", path: "/assets/basketball/nba/uta.png" },
    "Mpt_NBA21": { internalCode: "03_01_GSW", shortName: "GSW", name: "Golden State Warriors", path: "/assets/basketball/nba/gsw.png" },
    "Mpt_NBA22": { internalCode: "03_01_LAC", shortName: "LAC", name: "LA Clippers", path: "/assets/basketball/nba/lac.png" },
    "Mpt_NBA23": { internalCode: "03_01_LAL", shortName: "LAL", name: "Los Angeles Lakers", path: "/assets/basketball/nba/lal.png" },
    "Mpt_NBA24": { internalCode: "03_01_PHO", shortName: "PHO", name: "Phoenix Suns", path: "/assets/basketball/nba/pho.png" },
    "Mpt_NBA25": { internalCode: "03_01_SAC", shortName: "SAC", name: "Sacramento Kings", path: "/assets/basketball/nba/sac.png" },
    "Mpt_NBA26": { internalCode: "03_01_DAL", shortName: "DAL", name: "Dallas Mavericks", path: "/assets/basketball/nba/dal.png" },
    "Mpt_NBA27": { internalCode: "03_01_HOU", shortName: "HOU", name: "Houston Rockets", path: "/assets/basketball/nba/hou.png" },
    "Mpt_NBA28": { internalCode: "03_01_MEM", shortName: "MEM", name: "Memphis Grizzlies", path: "/assets/basketball/nba/mem.png" },
    "Mpt_NBA29": { internalCode: "03_01_NOP", shortName: "NOP", name: "New Orleans Pelicans", path: "/assets/basketball/nba/nop.png" },
    "Mpt_NBA30": { internalCode: "03_01_SAS", shortName: "SAS", name: "San Antonio Spurs", path: "/assets/basketball/nba/sas.png" }
};