// src/config/entityRegistry.ts

export const ENTITY_REGISTRY: Record<string, { internalCode: string, shortName: string, name: string }> = {
    "Mpt_MLB01": { "internalCode": "01_01_ARI", "shortName": "ARI", "name": "Arizona Diamondbacks" },
    "Mpt_MLB02": { "internalCode": "01_01_ATL", "shortName": "ATL", "name": "Atlanta Braves" },
    "Mpt_MLB03": { "internalCode": "01_01_BAL", "shortName": "BAL", "name": "Baltimore Orioles" },
    "Mpt_MLB04": { "internalCode": "01_01_BOS", "shortName": "BOS", "name": "Boston Red Sox" },
    "Mpt_MLB05": { "internalCode": "01_01_CHC", "shortName": "CHC", "name": "Chicago Cubs" },
    "Mpt_MLB06": { "internalCode": "01_01_CWS", "shortName": "CWS", "name": "Chicago White Sox" },
    "Mpt_MLB07": { "internalCode": "01_01_CIN", "shortName": "CIN", "name": "Cincinnati Reds" },
    "Mpt_MLB08": { "internalCode": "01_01_CLE", "shortName": "CLE", "name": "Cleveland Guardians" },
    "Mpt_MLB09": { "internalCode": "01_01_COL", "shortName": "COL", "name": "Colorado Rockies" },
    "Mpt_MLB10": { "internalCode": "01_01_DET", "shortName": "DET", "name": "Detroit Tigers" },
    "Mpt_MLB11": { "internalCode": "01_01_HOU", "shortName": "HOU", "name": "Houston Astros" },
    "Mpt_MLB12": { "internalCode": "01_01_KC", "shortName": "KC", "name": "Kansas City Royals" },
    "Mpt_MLB13": { "internalCode": "01_01_LAA", "shortName": "LAA", "name": "Los Angeles Angels" },
    "Mpt_MLB14": { "internalCode": "01_01_LAD", "shortName": "LAD", "name": "Los Angeles Dodgers" },
    "Mpt_MLB15": { "internalCode": "01_01_MIA", "shortName": "MIA", "name": "Miami Marlins" },
    "Mpt_MLB16": { "internalCode": "01_01_MIL", "shortName": "MIL", "name": "Milwaukee Brewers" },
    "Mpt_MLB17": { "internalCode": "01_01_MIN", "shortName": "MIN", "name": "Minnesota Twins" },
    "Mpt_MLB18": { "internalCode": "01_01_NYM", "shortName": "NYM", "name": "New York Mets" },
    "Mpt_MLB19": { "internalCode": "01_01_NYY", "shortName": "NYY", "name": "New York Yankees" },
    "Mpt_MLB20": { "internalCode": "01_01_OAK", "shortName": "OAK", "name": "Oakland Athletics" },
    "Mpt_MLB21": { "internalCode": "01_01_PHI", "shortName": "PHI", "name": "Philadelphia Phillies" },
    "Mpt_MLB22": { "internalCode": "01_01_PIT", "shortName": "PIT", "name": "Pittsburgh Pirates" },
    "Mpt_MLB23": { "internalCode": "01_01_SD", "shortName": "SD", "name": "San Diego Padres" },
    "Mpt_MLB24": { "internalCode": "01_01_SF", "shortName": "SF", "name": "San Francisco Giants" },
    "Mpt_MLB25": { "internalCode": "01_01_SEA", "shortName": "SEA", "name": "Seattle Mariners" },
    "Mpt_MLB26": { "internalCode": "01_01_STL", "shortName": "STL", "name": "St. Louis Cardinals" },
    "Mpt_MLB27": { "internalCode": "01_01_TB", "shortName": "TB", "name": "Tampa Bay Rays" },
    "Mpt_MLB28": { "internalCode": "01_01_TEX", "shortName": "TEX", "name": "Texas Rangers" },
    "Mpt_MLB29": { "internalCode": "01_01_TOR", "shortName": "TOR", "name": "Toronto Blue Jays" },
    "Mpt_MLB30": { "internalCode": "01_01_WSH", "shortName": "WSH", "name": "Washington Nationals" },
    "Mpt_NBA01": { "internalCode": "03_01_ATL", "shortName": "ATL", "name": "Atlanta Hawks" },
    "Mpt_NBA02": { "internalCode": "03_01_BOS", "shortName": "BOS", "name": "Boston Celtics" },
    "Mpt_NBA03": { "internalCode": "03_01_BKN", "shortName": "BKN", "name": "Brooklyn Nets" },
    "Mpt_NBA04": { "internalCode": "03_01_CHA", "shortName": "CHA", "name": "Charlotte Hornets" },
    "Mpt_NBA05": { "internalCode": "03_01_CHI", "shortName": "CHI", "name": "Chicago Bulls" },
    "Mpt_NBA06": { "internalCode": "03_01_CLE", "shortName": "CLE", "name": "Cleveland Cavaliers" },
    "Mpt_NBA07": { "internalCode": "03_01_DAL", "shortName": "DAL", "name": "Dallas Mavericks" },
    "Mpt_NBA08": { "internalCode": "03_01_DEN", "shortName": "DEN", "name": "Denver Nuggets" },
    "Mpt_NBA09": { "internalCode": "03_01_DET", "shortName": "DET", "name": "Detroit Pistons" },
    "Mpt_NBA10": { "internalCode": "03_01_GSW", "shortName": "GSW", "name": "Golden State Warriors" },
    "Mpt_NBA11": { "internalCode": "03_01_HOU", "shortName": "HOU", "name": "Houston Rockets" },
    "Mpt_NBA12": { "internalCode": "03_01_IND", "shortName": "IND", "name": "Indiana Pacers" },
    "Mpt_NBA13": { "internalCode": "03_01_LAC", "shortName": "LAC", "name": "LA Clippers" },
    "Mpt_NBA14": { "internalCode": "03_01_LAL", "shortName": "LAL", "name": "Los Angeles Lakers" },
    "Mpt_NBA15": { "internalCode": "03_01_MEM", "shortName": "MEM", "name": "Memphis Grizzlies" },
    "Mpt_NBA16": { "internalCode": "03_01_MIA", "shortName": "MIA", "name": "Miami Heat" },
    "Mpt_NBA17": { "internalCode": "03_01_MIL", "shortName": "MIL", "name": "Milwaukee Bucks" },
    "Mpt_NBA18": { "internalCode": "03_01_MIN", "shortName": "MIN", "name": "Minnesota Timberwolves" },
    "Mpt_NBA19": { "internalCode": "03_01_NOP", "shortName": "NOP", "name": "New Orleans Pelicans" },
    "Mpt_NBA20": { "internalCode": "03_01_NYK", "shortName": "NYK", "name": "New York Knicks" },
    "Mpt_NBA21": { "internalCode": "03_01_OKC", "shortName": "OKC", "name": "Oklahoma City Thunder" },
    "Mpt_NBA22": { "internalCode": "03_01_ORL", "shortName": "ORL", "name": "Orlando Magic" },
    "Mpt_NBA23": { "internalCode": "03_01_PHI", "shortName": "PHI", "name": "Philadelphia 76ers" },
    "Mpt_NBA24": { "internalCode": "03_01_PHX", "shortName": "PHX", "name": "Phoenix Suns" },
    "Mpt_NBA25": { "internalCode": "03_01_POR", "shortName": "POR", "name": "Portland Trail Blazers" },
    "Mpt_NBA26": { "internalCode": "03_01_SAC", "shortName": "SAC", "name": "Sacramento Kings" },
    "Mpt_NBA27": { "internalCode": "03_01_SAS", "shortName": "SAS", "name": "San Antonio Spurs" },
    "Mpt_NBA28": { "internalCode": "03_01_TOR", "shortName": "TOR", "name": "Toronto Raptors" },
    "Mpt_NBA29": { "internalCode": "03_01_UTA", "shortName": "UTA", "name": "Utah Jazz" },
    "Mpt_NBA30": { "internalCode": "03_01_WAS", "shortName": "WAS", "name": "Washington Wizards" },
    "Mpt_EPL01": { "internalCode": "02_01_ARS", "shortName": "ARS", "name": "Arsenal" },
    "Mpt_EPL02": { "internalCode": "02_01_AVL", "shortName": "AVL", "name": "Aston Villa" },
    "Mpt_EPL03": { "internalCode": "02_01_BHA", "shortName": "BHA", "name": "Brighton & Hove Albion" },
    "Mpt_EPL04": { "internalCode": "02_01_BOU", "shortName": "BOU", "name": "Bournemouth" },
    "Mpt_EPL05": { "internalCode": "02_01_BRE", "shortName": "BRE", "name": "Brentford" },
    "Mpt_EPL06": { "internalCode": "02_01_CHE", "shortName": "CHE", "name": "Chelsea" },
    "Mpt_EPL07": { "internalCode": "02_01_CRY", "shortName": "CRY", "name": "Crystal Palace" },
    "Mpt_EPL08": { "internalCode": "02_01_EVE", "shortName": "EVE", "name": "Everton" },
    "Mpt_EPL09": { "internalCode": "02_01_FUL", "shortName": "FUL", "name": "Fulham" },
    "Mpt_EPL10": { "internalCode": "02_01_IPS", "shortName": "IPS", "name": "Ipswich Town" },
    "Mpt_EPL11": { "internalCode": "02_01_LEI", "shortName": "LEI", "name": "Leicester City" },
    "Mpt_EPL12": { "internalCode": "02_01_LIV", "shortName": "LIV", "name": "Liverpool" },
    "Mpt_EPL13": { "internalCode": "02_01_MCI", "shortName": "MCI", "name": "Manchester City" },
    "Mpt_EPL14": { "internalCode": "02_01_MUN", "shortName": "MUN", "name": "Manchester United" },
    "Mpt_EPL15": { "internalCode": "02_01_NEW", "shortName": "NEW", "name": "Newcastle United" },
    "Mpt_EPL16": { "internalCode": "02_01_NFO", "shortName": "NFO", "name": "Nottingham Forest" },
    "Mpt_EPL17": { "internalCode": "02_01_SOU", "shortName": "SOU", "name": "Southampton" },
    "Mpt_EPL18": { "internalCode": "02_01_TOT", "shortName": "TOT", "name": "Tottenham Hotspur" },
    "Mpt_EPL19": { "internalCode": "02_01_WHU", "shortName": "WHU", "name": "West Ham United" },
    "Mpt_EPL20": { "internalCode": "02_01_WOL", "shortName": "WOL", "name": "Wolverhampton Wanderers" },
    "Mpt_ESP01": { "internalCode": "02_01_ALA", "shortName": "ALA", "name": "Alavés" },
    "Mpt_ESP02": { "internalCode": "02_01_ATH", "shortName": "ATH", "name": "Athletic Club" },
    "Mpt_ESP03": { "internalCode": "02_01_ATM", "shortName": "ATM", "name": "Atlético Madrid" },
    "Mpt_ESP04": { "internalCode": "02_01_BAR", "shortName": "BAR", "name": "Barcelona" },
    "Mpt_ESP05": { "internalCode": "02_01_CEL", "shortName": "CEL", "name": "Celta Vigo" },
    "Mpt_ESP06": { "internalCode": "02_01_ESP", "shortName": "ESP", "name": "Espanyol" },
    "Mpt_ESP07": { "internalCode": "02_01_GET", "shortName": "GET", "name": "Getafe" },
    "Mpt_ESP08": { "internalCode": "02_01_GIR", "shortName": "GIR", "name": "Girona" },
    "Mpt_ESP09": { "internalCode": "02_01_LVB", "shortName": "LVB", "name": "Las Palmas" },
    "Mpt_ESP10": { "internalCode": "02_01_LEG", "shortName": "LEG", "name": "Leganés" },
    "Mpt_ESP11": { "internalCode": "02_01_MLL", "shortName": "MLL", "name": "Mallorca" },
    "Mpt_ESP12": { "internalCode": "02_01_OSA", "shortName": "OSA", "name": "Osasuna" },
    "Mpt_ESP13": { "internalCode": "02_01_RAY", "shortName": "RAY", "name": "Rayo Vallecano" },
    "Mpt_ESP14": { "internalCode": "02_01_BET", "shortName": "BET", "name": "Real Betis" },
    "Mpt_ESP15": { "internalCode": "02_01_RMA", "shortName": "RMA", "name": "Real Madrid" },
    "Mpt_ESP16": { "internalCode": "02_01_RSO", "shortName": "RSO", "name": "Real Sociedad" },
    "Mpt_ESP17": { "internalCode": "02_01_SEV", "shortName": "SEV", "name": "Sevilla" },
    "Mpt_ESP18": { "internalCode": "02_01_VAL", "shortName": "VAL", "name": "Valencia" },
    "Mpt_ESP19": { "internalCode": "02_01_VLD", "shortName": "VLD", "name": "Real Valladolid" },
    "Mpt_ESP20": { "internalCode": "02_01_VIL", "shortName": "VIL", "name": "Villarreal" },
    "Mpt_ITA01": { "internalCode": "02_01_MIL", "shortName": "MIL", "name": "AC Milan" },
    "Mpt_ITA02": { "internalCode": "02_01_ROMA", "shortName": "ROMA", "name": "AS Roma" },
    "Mpt_ITA03": { "internalCode": "02_01_ATA", "shortName": "ATA", "name": "Atalanta" },
    "Mpt_ITA04": { "internalCode": "02_01_BOL", "shortName": "BOL", "name": "Bologna" },
    "Mpt_ITA05": { "internalCode": "02_01_CAG", "shortName": "CAG", "name": "Cagliari" },
    "Mpt_ITA06": { "internalCode": "02_01_COMO", "shortName": "COMO", "name": "Como" },
    "Mpt_ITA07": { "internalCode": "02_01_EMP", "shortName": "EMP", "name": "Empoli" },
    "Mpt_ITA08": { "internalCode": "02_01_FIO", "shortName": "FIO", "name": "Fiorentina" },
    "Mpt_ITA09": { "internalCode": "02_01_GEN", "shortName": "GEN", "name": "Genoa" },
    "Mpt_ITA10": { "internalCode": "02_01_VER", "shortName": "VER", "name": "Hellas Verona" },
    "Mpt_ITA11": { "internalCode": "02_01_INT", "shortName": "INT", "name": "Internazionale" },
    "Mpt_ITA12": { "internalCode": "02_01_JUV", "shortName": "JUV", "name": "Juventus" },
    "Mpt_ITA13": { "internalCode": "02_01_LAZ", "shortName": "LAZ", "name": "Lazio" },
    "Mpt_ITA14": { "internalCode": "02_01_LEC", "shortName": "LEC", "name": "Lecce" },
    "Mpt_ITA15": { "internalCode": "02_01_MON", "shortName": "MON", "name": "Monza" },
    "Mpt_ITA16": { "internalCode": "02_01_NAP", "shortName": "NAP", "name": "Napoli" },
    "Mpt_ITA17": { "internalCode": "02_01_PAR", "shortName": "PAR", "name": "Parma" },
    "Mpt_ITA18": { "internalCode": "02_01_SAS", "shortName": "SAS", "name": "Sassuolo" },
    "Mpt_ITA19": { "internalCode": "02_01_TOR", "shortName": "TOR", "name": "Torino" },
    "Mpt_ITA20": { "internalCode": "02_01_UDI", "shortName": "UDI", "name": "Udinese" },
    "Mpt_GER01": { "internalCode": "02_01_HDH", "shortName": "HDH", "name": "1. FC Heidenheim 1846" },
    "Mpt_GER02": { "internalCode": "02_01_FCU", "shortName": "FCU", "name": "1. FC Union Berlin" },
    "Mpt_GER03": { "internalCode": "02_01_B04", "shortName": "B04", "name": "Bayer Leverkusen" },
    "Mpt_GER04": { "internalCode": "02_01_MUN", "shortName": "MUN", "name": "Bayern Munich" },
    "Mpt_GER05": { "internalCode": "02_01_DOR", "shortName": "DOR", "name": "Borussia Dortmund" },
    "Mpt_GER06": { "internalCode": "02_01_BMG", "shortName": "BMG", "name": "Borussia Mönchengladbach" },
    "Mpt_GER07": { "internalCode": "02_01_SGE", "shortName": "SGE", "name": "Eintracht Frankfurt" },
    "Mpt_GER08": { "internalCode": "02_01_FCA", "shortName": "FCA", "name": "FC Augsburg" },
    "Mpt_GER09": { "internalCode": "02_01_KOE", "shortName": "KOE", "name": "FC Cologne" },
    "Mpt_GER10": { "internalCode": "02_01_HSV", "shortName": "HSV", "name": "Hamburg SV" },
    "Mpt_GER11": { "internalCode": "02_01_HOL", "shortName": "HOL", "name": "Holstein Kiel" },
    "Mpt_GER12": { "internalCode": "02_01_M05", "shortName": "M05", "name": "Mainz" },
    "Mpt_GER13": { "internalCode": "02_01_RBL", "shortName": "RBL", "name": "RB Leipzig" },
    "Mpt_GER14": { "internalCode": "02_01_SCF", "shortName": "SCF", "name": "SC Freiburg" },
    "Mpt_GER15": { "internalCode": "02_01_STP", "shortName": "STP", "name": "St. Pauli" },
    "Mpt_GER16": { "internalCode": "02_01_TSG", "shortName": "TSG", "name": "TSG Hoffenheim" },
    "Mpt_GER17": { "internalCode": "02_01_VFB", "shortName": "VFB", "name": "VfB Stuttgart" },
    "Mpt_GER18": { "internalCode": "02_01_WOB", "shortName": "WOB", "name": "VfL Wolfsburg" },
    "Mpt_GER19": { "internalCode": "02_01_SVW", "shortName": "SVW", "name": "Werder Bremen" },
    "Mpt_FRA01": { "internalCode": "02_01_AUX", "shortName": "AUX", "name": "AJ Auxerre" },
    "Mpt_FRA02": { "internalCode": "02_01_MON", "shortName": "MON", "name": "AS Monaco" },
    "Mpt_FRA03": { "internalCode": "02_01_ANG", "shortName": "ANG", "name": "Angers" },
    "Mpt_FRA04": { "internalCode": "02_01_BRE", "shortName": "BRE", "name": "Brest" },
    "Mpt_FRA05": { "internalCode": "02_01_HAC", "shortName": "HAC", "name": "Le Havre AC" },
    "Mpt_FRA06": { "internalCode": "02_01_RCL", "shortName": "RCL", "name": "Lens" },
    "Mpt_FRA07": { "internalCode": "02_01_LILL", "shortName": "LILL", "name": "Lille" },
    "Mpt_FRA08": { "internalCode": "02_01_LOR", "shortName": "LOR", "name": "Lorient" },
    "Mpt_FRA09": { "internalCode": "02_01_LYON", "shortName": "LYON", "name": "Lyon" },
    "Mpt_FRA10": { "internalCode": "02_01_OLM", "shortName": "OLM", "name": "Marseille" },
    "Mpt_FRA11": { "internalCode": "02_01_METZ", "shortName": "METZ", "name": "Metz" },
    "Mpt_FRA12": { "internalCode": "02_01_MPL", "shortName": "MPL", "name": "Montpellier" },
    "Mpt_FRA13": { "internalCode": "02_01_NAN", "shortName": "NAN", "name": "Nantes" },
    "Mpt_FRA14": { "internalCode": "02_01_NICE", "shortName": "NICE", "name": "Nice" },
    "Mpt_FRA15": { "internalCode": "02_01_PAR", "shortName": "PAR", "name": "Paris FC" },
    "Mpt_FRA16": { "internalCode": "02_01_PSG", "shortName": "PSG", "name": "Paris Saint-Germain" },
    "Mpt_FRA17": { "internalCode": "02_01_REN", "shortName": "REN", "name": "Stade Rennais" },
    "Mpt_FRA18": { "internalCode": "02_01_STR", "shortName": "STR", "name": "Strasbourg" },
    "Mpt_FRA19": { "internalCode": "02_01_TOU", "shortName": "TOU", "name": "Toulouse" }
};

// Reverse lookup for V2 DB binding: internal_code -> hashId
export const REVERSE_REGISTRY: Record<string, string> = Object.entries(ENTITY_REGISTRY).reduce(
    (acc, [hash, entity]) => ({ ...acc, [entity.internalCode]: hash }),
    {}
);