export const TEAM_LOGOS: Record<string, string> = {
  MLB_LAD: '/logos/mlb/lad.png',
  MLB_NYY: '/logos/mlb/nyy.png',
  MLB_SFG: '/logos/mlb/sfg.png',
  MLB_CHW: '/logos/mlb/chw.png',
  MLB_WSH: '/logos/mlb/wsh.png',

  NBA_LAL: '/logos/nba/lal.png',
  NBA_GSW: '/logos/nba/gsw.png',
  NBA_NYK: '/logos/nba/nyk.png',
  NBA_PHX: '/logos/nba/phx.png',
  NBA_NOP: '/logos/nba/nop.png',
  NBA_SAS: '/logos/nba/sas.png',
  NBA_WAS: '/logos/nba/was.png',
  NBA_OKC: '/logos/nba/okc.png',
  NBA_DEN: '/logos/nba/den.png',
  NBA_MIN: '/logos/nba/min.png',
  NBA_CLE: '/logos/nba/cle.png',
  NBA_BOS: '/logos/nba/bos.png',
  NBA_DET: '/logos/nba/det.png',
  NBA_ATL: '/logos/nba/atl.png',
  NBA_TOR: '/logos/nba/tor.png',
  NBA_ORL: '/logos/nba/orl.png',
  NBA_PHI: '/logos/nba/phi.png',
  NBA_POR: '/logos/nba/por.png',
  NBA_HOU: '/logos/nba/hou.png',

  EPL_ARS: '/logos/epl/ars.png',
  EPL_MCI: '/logos/epl/mci.png',
  EPL_MUN: '/logos/epl/mun.png',
  EPL_TOT: '/logos/epl/tot.png',
}
